# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilogenie111', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModelForSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaa', models.TextField()),
                ('bbb', models.TextField()),
                ('ccc', models.TextField()),
            ],
        ),
    ]
